name: swipe_maze
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  loop_page_view: ^1.0.9
  matrix_gesture_detector: ^0.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true